version: '2'
services:
  worker:
    build: .
    command: ["celery", "-A", "app:celery", "worker", "-l", "info"]
  flower:
    extends:
      service: worker
    command: ["celery", "-A", "app:celery", "flower"]
    depends_on:
     - rabbit
    ports:
     - "5555:5555"
  web:
    extends:
      service: worker
    environment:
      - FLASK_APP=app.py
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
     - "5000:5000"
  api:
    extends:
      service: worker
    environment:
      - FLASK_APP=app.py
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
     - "5001:5000"
  locust:
    extends:
      service: worker
    command: ["locust", "--host=http://web:5000"]
    depends_on:
      - web
      - api
    ports:
     - "8089:8089"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "15672:15672"
